'use strict';

module.exports = {
	'1000' : 'Invalid request.',
	'1001' : 'Technical error.',
	'7000' : 'Invalid XML',
	'7004' : 'XML parameter not provided in request',
	'7005' : 'Project has no Deutsche Handelsbank account.',
	'7006' : 'Service temporarily unavailable due to maintenance',
	'8000' : 'No project ID provided',
	'8001' : 'Unknown project',
	'8002' : 'Validation Error',
	'8003' : 'Request could not be processed',
	'8004' : 'No product is selected',
	'8006' : 'Logic error.',
	'8010' : 'must not be empty',
	'8011' : 'not in list of valid values',
	'8012' : 'must be a positive number',
	'8013' : 'unsupported currency',
	'8014' : 'invalid amount',
	'8015' : 'amount is out of range',
	'8016' : 'must be a valid url	',
	'8017' : 'invalid chars',
	'8018' : 'maximum length of 27 chars exceeded',
	'8019' : 'invalid email address',
	'8020' : 'invalid phone number',
	'8021' : 'invalid country code',
	'8022' : 'unsupported country code',
	'8023' : 'invalid BIC',
	'8025' : 'must be 2 or 3 // salutation',
	'8026' : 'must be a boolean, either 0 or 1',
	'8027' : 'product not activated and not in testmode',
	'8028' : 'locked_sender_country_id is activated in project settings, but not provided',
	'8040' : 'No amount with comma allowed for HU.',
	'8042' : 'consumer protection is only available for sender accounts from DE, AT and CH',
	'8045' : 'product in testmode and given bank_code is not a test bank code',
	'8046' : 'validation of given bank account and bank code failed',
	'8047' : 'Maximum length of 255 characters exceeded.',
	'8049' : 'unsupported language',
	'8050' : 'value too small. setting timeout to minimum value.',
	'8051' : 'invalid items found',
	'8054' : 'all products deactivated due to errors. Initiation aborted',
	'8057' : 'activate this product in your project settings',
	'8058' : 'payment not possible with this service',
	'8059' : 'sender country not supported for this currency',
	'8060' : 'Blacklisted',
	'8063' : 'No success_url provided in request and in project settings',
	'8064' : 'No abort_url provided in request and in project settings',
	'8072' : 'maximum number of notification exceeded',
	'8073' : 'Maximum number of user variables exceeded',
	'7999' : 'Out of range (Too many entries or invalid values for the site)',
	'8005' : 'Too many transactions requested',
	'8007' : 'Invalid date format. Format is YYYY-MM-DD [HH:MM:SS]',
	'8008' : 'from_time equals to_time',
	'8009' : 'max date range exceeded'
};
